[package]
name = "emulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.24"
rodio = "0.17"
gilrs = "0.10.2"

[profile.dev]
overflow-checks = false
